### ISSUE TITLE
Crash - unrecognized selector sent to instance

### ISSUE THREAD

**Issue by Csaba8472** [thisisthekap/Xamarin.RevenueCat.iOS#13]
First of all, thank you for the library!

With the latest Xamarin.iOS - xcode versions when I try to init RCPurchases:
`
RCPurchases.DebugLogsEnabled = true;
RCPurchases.ConfigureWithAPIKey(API_KEY);
`

I get this exception:
```[RCPurchases configureSubscriberAttributesManager]: unrecognized selector sent to instance```

and RCPurchases.SharedPurchases is not initialised.

Full log:
``` [Purchases] - DEBUG: SDK Version - 3.5.3
[Purchases] - DEBUG: Initial App User ID - (null)
[Purchases] - DEBUG: Generated New App User ID - $RCAnonymousID:e8002ee99a544cfe848e6b4dc4dcff36
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:e8002ee99a544cfe848e6b4dc4dcff36
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:e8002ee99a544cfe848e6b4dc4dcff36/offerings
-[RCPurchases configureSubscriberAttributesManager]: unrecognized selector sent to instance 0x28354d0e0
[Purchases] - DEBUG: GET /v1/subscribers/$RCAnonymousID:e8002ee99a544cfe848e6b4dc4dcff36/offerings 200
[Purchases] - DEBUG: Requesting products with identifiers: {(
```

Tried 3.5.3.10 and 3.5.3.8 and both had this issue.

Also tried to update, but it seems from [3.6.0](https://github.com/RevenueCat/purchases-ios/releases/tag/3.6.0) the lib is modularized, and it has swift code too, so this method didn't work.

What did I do wrong?

**Comment by thisisthekap** [comment]
@Csaba8472 Everything seems to be working just fine on our side (also when using newest xcode/sdks).

I will try to investigate the issue in detail today or tomorrow.

**Comment by thisisthekap** [comment]
@Csaba8472 Tried to reproduce this issue. No success. What device and os are you deploying to?

**Comment by Csaba8472** [comment]
The easiest way is to create a new single view project, add Xamarin.RevenueCat.iOS and Xamarin.RevenueCat.iOS.Extensions and call it:
```
RCPurchases.DebugLogsEnabled = true; RCPurchases.ConfigureWithAPIKey(API_KEY);

```

![revcattest](https://user-images.githubusercontent.com/483692/106516314-28c9eb80-64d7-11eb-885d-e09d49acfb1d.png)
(removed the API key before I created the screenshot)

Tried to run it on simulator with iOS 14.3. I don't think that simulator is the problem because revenuecat's native lib doesn't crash.

**Comment by thisisthekap** [comment]
@Csaba8472 Thanks for that, will try to have a look into that one later today.

**Comment by thisisthekap** [comment]
Current state:

1. I am able to reproduce the issue using a new project
2. Our own usage of the nugets is working just fine (xamarin forms solution)
3. The UsageChecker project ist working just fine

Currently, I have no clue on the cause of this issue. Further investigation is needed.

@Csaba8472 Do you know additional details, or hints on possible causes?

**Comment by thisisthekap** [comment]
@Csaba8472 I think I got it.

Please try to add `<MtouchExtraArgs>-gcc_flags "-ObjC"</MtouchExtraArgs>` to your project file.

If you prefer the UI dialog:
![image](https://user-images.githubusercontent.com/9071974/107922715-b5ad8400-6f70-11eb-81f2-49649a0881bb.png)

**Comment by Csaba8472** [comment]
Thank you that solved the issue. In the meantime, I've wrapped RevenueCat's newest lib, do you plan to release an update to this lib which supports the newest RevenueCat lib?

**Comment by thisisthekap** [comment]
@Csaba8472 Awsome!

So you successfully created Xamarin.iOS Bindings for the newest version of the RevenueCat SDK? If so: A PR would be very much appreciated!😎

**Comment by thisisthekap** [comment]
As #14 documents this fix in README.md, I think this issue can be closed. @Csaba8472 Do you agree?

**Comment by thisisthekap** [comment]
@Csaba8472 Did you manage to create the Xamarin.iOS Bindings for the newest version of the RevenueCat SDK?

**Comment by Csaba8472** [comment]
Yep, I agree, thank you for investigating it. Sort of, as the newest sdk is in swift I couldn't manually generate all the methods, instead I only wrapped the swift methods to objc which I needed and then I could bind those methods.

**Comment by thisisthekap** [comment]
@Csaba8472 As this imho is currently the only way to do propper swift bindings (https://github.com/xamarin/binding-tools-for-swift will most likely take some time to become stable), I think your new bindings are definitely worth a contribution.

Looking forward to your PR! 😊

**Comment by thisisthekap** [comment]
@Csaba8472 Did you manage to create a working wrapper for the swift library?

**Comment by Csaba8472** [comment]
sorry forgot to write, still haven't had time to wrap all the methods. My current approach is creating a slim binding around RevenueCat.

**Comment by thisisthekap** [comment]
I am willing to assist you on that.

If you agree: Please create a PR, mark it as draft, and add me as a contributor to your fork.

**Comment by Csaba8472** [comment]
Uploaded what I currently have. As it needs different approach, we have to start the project from the grund up. You can check it [here](https://github.com/Csaba8472/revenuecat-purchases-ios).

**Comment by thisisthekap** [comment]
@Csaba8472 Thank you very much!

As of now, i do not know when I am going to find the time to do the upgrade.

Your contribution is going to help me a fortune when doing so!

**Comment by Csaba8472** [comment]
@thisisthekap I'm open to work on it, can you join to [DotNetEvolution](https://aka.ms/dotnet-discord) discord channel? We could chat there easier.

**Comment by thisisthekap** [comment]
@Csaba8472 My name in DotNetEvolution Discord: thekap#4353

**Comment by Csaba8472** [comment]
can't find you, I'm Csaba8472 could you please ping me?

**Comment by thisisthekap** [comment]
@Csaba8472 whats the username incl. tag? (The number after the # in your Discord name)
