### ISSUE TITLE
RCPurchasesErrorDomain trying to check subscriptions

### ISSUE THREAD

**Issue by dmanning23** [thisisthekap/Xamarin.RevenueCat.iOS#15]
Thanks for maintaining this library! I am also using the the Android version, which is live in the playstore and works great :)
However I'm having problems getting subscriptions working on iOS... 
When it tries to retrieve the user's receipt using SharedPurchases.RestoreTransactions, I get a PurchasesErrorCode of Purchases.RCPurchasesErrorCode.MissingReceiptFileError:
Error Domain=RCPurchasesErrorDomain Code=9 "The receipt is missing."

I figured it was just the sandbox being squirrelly, but I'm also seeing it on TestFlight.
Any help super appreciated. Cheers!

**Comment by thisisthekap** [comment]
@dmanning23 Can you share the code snipped you are using to restore the purchases including the init call and the mtouchargs section of the project file?

**Comment by dmanning23** [comment]
Sure, thanks for taking a look. Here is

**Comment by thisisthekap** [comment]
Seems to be related to https://github.com/RevenueCat/react-native-purchases/issues/88

**Comment by dmanning23** [comment]
Got it, yeah after I asked the question I was like "I wonder if that just means the user doesn't have a subscription?" Looks like I got my answer :+1:

**Comment by thisisthekap** [comment]
@dmanning23 You are welcome.
