### ISSUE TITLE
small example project needed

### ISSUE THREAD

**Issue by sjorsmiltenburg** [thisisthekap/Xamarin.RevenueCat.iOS#21]
Hi, I would love to use your packages, but I find I need a small example project in order to get up and running.

Am i supposed to include both the nuget package xamarin.revenuecat.ios AND xamarin.revenuecat.ios.extensions?

if i add them both i would expect the method GetCustomerInfoAsync to be added to the RCPurchases class, but it is not.

```

         public async Task<bool> HasActiveSubscription()
        {
            //reading the code, this is what I would expect to be the aimed method of using your library.
            //however, this does not work, because it does not recognize the method GetCustomerInfoAsync()
            var customerInfo = await RCPurchases.GetCustomerInfoAsync(); 

            //by using RCPurchasesExtensions I can get hold of the GetcustomerInfoAsync method, but i need an instance of RCPurchases., but as this is an extension method referencing 'this' i suspect your intention is it should work like the line above.
            var customerInfo2 = await RCPurchasesExtensions.GetCustomerInfoAsync(RCPurchases.SharedPurchases);
        }
```

any help would be much appreciated

**Comment by sjorsmiltenburg** [comment]
i found a code sample on one of the other issues, apperently i need to use

await RCPurchases.SharedPurchases.GetCustomerInfoAysnc();

**Comment by thisisthekap** [comment]
Please refer to the Swift examples provided by RevenueCat. The calls given there are easily transferrable to C#.

**Comment by thisisthekap** [comment]
Closing this one. Please comment if you think this one should stay open.

**Comment by sjorsmiltenburg** [comment]
I would be willing to share my code 'as a sample' to help others out

**Comment by norton287** [comment]
@sjorsmiltenburg I would be interested in your sample code.  I am kind of at a loss at some points in getting started!

**Comment by norton287** [comment]
@sjorsmiltenburg Thank you so much for that I will go through it and work it into my project.  If I come upon any unwritten revelations I will share them with you for sure.  Hang on to my email address for sure.

Thank you again!

**Comment by norton287** [comment]
@sjorsmiltenburg What am I missing I'm getting type or namespace errors with:

IRevenueCatPurchasesService
IDeviceInfoService
RevenueCatPurchaseResult

I've taken your code directly and installed all the packages.  What could I be missing?

**Comment by sjorsmiltenburg** [comment]
those are related to my own code, you can do without them.

IRevenueCatPurchaseService is an abstraction for mocking / dependency injection
IDeviceInfoService has the role to determine if the device we are running on is a developer device 

The RevenueCatPurchaseResult is maybe the most interesting one. It's a class to give back a result from my iOS project to my cross platform xamarin code. Not all error codes are failures that need to be handled the same way, and the errors need to be localised in the cross platorm part of my app.

```
public class RevenueCatPurchaseResult
    {
        public bool Success { get; set; }
        public MyRcErrorCodes ErrorForUserTranslationKey { get; set; } = MyRcErrorCodes.ShowNoError;
        public string ErrorForBackend { get; set; }
    }
```

**Comment by norton287** [comment]
@sjorsmiltenburg ahhh I see what you are saying.  Thank you for the quick response!

**Comment by BillFulton** [comment]
@sjorsmiltenburg @norton287 Guys, I have a working Xamarin Forms RevenueCat app (iOS only atm). It's gone through developer sandbox but was not planning to publish till it's production tested. However if it's of any use, happy to share the iOS side with you any time. Let me know.  Btw @thisisthekap, I'm so impressed with what you've done here. Cheers, Bill.

**Comment by norton287** [comment]
Bill

Anything you can contribute would be absolutely fantastic.  I'm sure it is above and beyond a fine example of work!

John


From: Bill ***@***.******@***.***>
Reply: thisisthekap/Xamarin.RevenueCat.iOS ***@***.******@***.***>
Date: October 11, 2022 at 7:12:14 AM
To: thisisthekap/Xamarin.RevenueCat.iOS ***@***.******@***.***>
CC: John Norton ***@***.******@***.***>, Mention ***@***.******@***.***>
Subject:  Re: [thisisthekap/Xamarin.RevenueCat.iOS] small example project needed (Issue #21)


@sjorsmiltenburg<https://github.com/sjorsmiltenburg> @norton287<https://github.com/norton287> Guys, I have a working Xamarin Forms RevenueCat app (iOS only atm). It's gone through developer sandbox but was not planning to publish till it's production tested. However if it's of any use, happy to share the iOS side with you any time. Let me know. Btw @thisisthekap<https://github.com/thisisthekap>, I'm so impressed with what you've done here. Cheers, Bill.

**Comment by BillFulton** [comment]
@norton287 Sure, I should be able to send it to you tomorrow. Pls bear in mind I am not a professional developer, so you'll see infelicities, but it works.  :)  Cheers Bill

**Comment by norton287** [comment]
I don't think that any of us are pros here so no worries Bill!

John


From: Bill ***@***.******@***.***>
Reply: thisisthekap/Xamarin.RevenueCat.iOS ***@***.******@***.***>
Date: October 11, 2022 at 7:26:51 AM
To: thisisthekap/Xamarin.RevenueCat.iOS ***@***.******@***.***>
CC: John Norton ***@***.******@***.***>, Mention ***@***.******@***.***>
Subject:  Re: [thisisthekap/Xamarin.RevenueCat.iOS] small example project needed (Issue #21)


@norton287<https://github.com/norton287> Sure, I should be able to send it to you tomorrow. Pls bear in mind I am not a professional developer, so you'll see infelicities, but it works. :) Cheers Bill
