### ISSUE TITLE
support armv7s architecture

### ISSUE THREAD

**Issue by sjorsmiltenburg** [thisisthekap/Xamarin.RevenueCat.iOS#24]
When packaging my app with your library I run into this 'problem'.

error MT5209 : Native linking error : warning: ignoring file  [mypath]obj/iPhone/Release/mtouch-cache/RevenueCat.framework/RevenueCat, file is universal (x86_64,arm64) but does not contain the armv7s architecture:

because it is ignored it will not find the RC files when building for this version.

the armv7s architecture is old, and you might not want to support it, i'm just logging this because maybe supporting it is just a checkbox that can be made active.

**Comment by thisisthekap** [comment]
Support would be easy codewise, but would increase the size of the library, and therefore the size of the resulting app. Most importantly, I have no such device lying around to test this architecture. Therefore I am not able to support it in a meaningful manner.

**Comment by sjorsmiltenburg** [comment]
i also don't have a device with this architecture at hand

**Comment by thisisthekap** [comment]
I think we got 2 options:

1. Dropping iOS 11 support for this binding (there are no devices >= iOS 12 with this architecture)
2. Adding the architecture (which seems dangerous because we have no feasible way to test it)

I would go for dropping iOS 11 support. @sjorsmiltenburg What do you think?

**Comment by sjorsmiltenburg** [comment]
Option 3 would be leave it as is.
It was a warning that was quite easy to fix.
Then you don't have to drop support for iOS 11.

What would be a reason for a device to still run iOS 11 now, 4 years later anyway?
Even my 7 year old iPad mini 4 is running iOS 14.

**Comment by thisisthekap** [comment]
I just found put that this is no issue anyways. RevenueCat supports > iOS 11. The devices running armv7 are stuck at iOS 10.

But I suggest to create a follow up workitem which defines the os compatibility the same way as RevenueCat does (so by setting it to iOS 11).

**Comment by thisisthekap** [comment]
For reference:

* https://docs-origin.revenuecat.com/docs/ios
* https://www.innerfence.com/howto/apple-ios-devices-dates-versions-instruction-sets
