### ISSUE TITLE
Sample code for iOS and Android

### ISSUE THREAD

**Issue by BillFulton** [thisisthekap/Xamarin.RevenueCat.iOS#30]
Hi. I posted sample code for iOS and Android at [https://stackoverflow.com/questions/75541953/sample-code-for-revenuecat-in-app-functions-in-xamarin-forms-or-net-maui](url). Hope it helps.

Cheers
Bill

**Comment by thisisthekap** [comment]
Hi @BillFulton,

thanks for the sample code!

Am I allowed to put the link to the GitHub repository in the README.md of this one? (of course while mentioning you as creator)

**Comment by BillFulton** [comment]
Hey, you are most welcome, thisisthekap.

I’m not a hot coder but it works!

Absolutely terrific job you have done.

Cheers
Bill
