### ISSUE TITLE
Crash if RevenueCat server certificate is invalid (iOS)

### ISSUE THREAD

**Issue by BillFulton** [thisisthekap/Xamarin.RevenueCat.iOS#32]
Hi ThisIsTheKap

I think possibly a certificate problem at api.revenuecat.com is not handled. I've recently had crashes on two different dates with the following log and do not see a way to handle it in code.

Cheers
Bill

0x1003d4000 + 51901116
SIGABRT: Error Domain=RevenueCat.ErrorCode Code=10 "Error performing request." UserInfo={source_file=RevenueCat/HTTPClient.swift:352, NSUnderlyingError=0x281e01980 {Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “api.revenuecat.com” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=( "<cert(0x1074ee200) s: FGT60FTK22099E6Y i: fortinet-subca2001>", "<cert(0x1074eea00) s: fortinet-subca2001 i: fortinet-ca2>", "<cert(0x1074ef600) s: fortinet-ca2 i: fortinet-ca2>" ), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://api.revenuecat.com/v1/subscribers/$RCAnonymousID%3A4b0c93ab91fe466e8bf2238ddcb80fe6/offerings, NSErrorFailingURLStringKey=https://api.revenuecat.com/v1/subscribers/$RCAnonymousID%3A4b0c93ab91fe466e8bf2238ddcb80fe6/offerings, NSUnderlyingError=0x281efd890 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x282185b80>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9807, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9807, kCFStreamPropertySSLPeerCertificates=( "<cert(0x1074ee200) s: FGT60FTK22099E6Y i: fortinet-subca2001>", "<cert(0x1074eea00) s: fortinet-subca2001 i: fortinet-ca2>", "<cert(0x1074ef600) s: fortinet-ca2 i: fortinet-ca2>" )}}, _NSURLErrorRelatedURLSessionTaskErrorKey=( "LocalDataTask <CD6D329D-D252-42D5-AC2E-40E10F22AFEE>.<2>" ), _kCFStreamErrorCodeKey=-9807, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <CD6D329D-D252-42D5-AC2E-40E10F22AFEE>.<2>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x282185b80>, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “api.revenuecat.com” which could put your confidential information at risk.}}, NSLocalizedDescription=Error performing request., source_function=init(_:dnsChecker:), readable_error_code=NETWORK_ERROR}

**Comment by thisisthekap** [comment]
Looks related to https://github.com/RevenueCat/purchases-ios/issues/2154 and https://github.com/RevenueCat/purchases-ios/issues/1900

Looks like some of your users are using a MITM proxy. Either they are aware of it, and so so to do something nasty or for technical research, or they are unaware of it, because the proxy is configured on a network (company) level.

Does wrapping the crashing call in try/catch and reporting the error in a meaningful way to the user mitigate your issue?

**Comment by BillFulton** [comment]
Thanks for the helpful response.

>> Does wrapping the crashing call in try/catch ...

Yes it is already in try/catch, and if I could detect the condition in the exception status, it would be fine. My issue is, I'm not sure what part of the above log text might be included in the exception status, and of course no way to test whether my guess would be correct.

**Comment by BillFulton** [comment]
Looks like I simply needed to check for PurchasesErrorCode.NetworkError.
