### ISSUE TITLE
Crash when initialising (iOS)

### ISSUE THREAD

**Issue by BillFulton** [thisisthekap/Xamarin.RevenueCat.iOS#33]
I've also been seeing occasional crashes when initialising RevenueCat on startup with crash logs like the following. I don't know if the logs would be of any use.

Cheers
Bill

InAppPurchases+<>c__DisplayClass13_0.<InitialiseRevenueCatAsync>b__0 ()
SIGABRT: Objective-C exception thrown. Name: NSInvalidArgumentException Reason: -[NSError underlyingErrors]: unrecognized selector sent to instance 0x280368cf0 Native stack trace: 0 CoreFoundation 0x00000001ab973604 409609CD-8410-38E1-BA5D-BDED609D2018 + 1222148 1 libobjc.A.dylib 0x00000001ab695bcc objc_exception_throw + 56 2 CoreFoundation 0x00000001ab877ea8 409609CD-8410-38E1-BA5D-BDED609D2018 + 192168 3 CoreFoundation 0x00000001ab977694 409609CD-8410-38E1-BA5D-BDED609D2018 + 1238676 4 CoreFoundation 0x00000001ab9795bc _CF_forwarding_prep_0 + 92 5 Behayve.iOS 0x00000001019688d0 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 17479404 6 Behayve.iOS 0x00000001018893e4 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 16564736 7 Behayve.iOS 0x0000000100924f50 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 425324 8 Behayve.iOS 0x0000000101882614 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 16536624 9 Behayve.iOS 0x0000000100cdd9c0 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 4327388 10 Behayve.iOS 0x00000001031c8a88 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43038884 11 Behayve.iOS 0x00000001032826d4 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43799792 12 Behayve.iOS 0x0000000103285f14 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43814192 13 Behayve.iOS 0x00000001008bdfb0 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 3532 14 Behayve.iOS 0x00000001008c7fa8 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 44484 15 Foundation 0x00000001abd5db28 1A46239D-F2FC-34B6-95BC-9F38869F0C85 + 1272616 16 CoreFoundation 0x00000001ab8f1b64 409609CD-8410-38E1-BA5D-BDED609D2018 + 691044 17 CoreFoundation 0x00000001ab8f1abc 409609CD-8410-38E1-BA5D-BDED609D2018 + 690876 18 CoreFoundation 0x00000001ab8f1244 409609CD-8410-38E1-BA5D-BDED609D2018 + 688708 19 CoreFoundation 0x00000001ab8ec274 409609CD-8410-38E1-BA5D-BDED609D2018 + 668276 20 CoreFoundation 0x00000001ab8ebc34 CFRunLoopRunSpecific + 424 21 GraphicsServices 0x00000001b5a3538c GSEventRunModal + 160 22 UIKitCore 0x00000001afa1e22c UIApplicationMain + 1932 23 libTweaks.dylib 0x00000001045f50cc _ZL25_apdecr_UIApplicationMainiPPcP8NSStringS2_ + 104 24 Behayve.iOS 0x000000010334f854 xamarin_UIApplicationMain + 24 25 Behayve.iOS 0x0000000101966a1c _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 17471544 26 Behayve.iOS 0x00000001018bb9c4 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 16771040 27 Behayve.iOS 0x00000001018bbb40 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 16771420 28 Behayve.iOS 0x0000000100905560 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 295804 29 Behayve.iOS 0x0000000100cdd9c0 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 4327388 30 Behayve.iOS 0x00000001031c8a88 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43038884 31 Behayve.iOS 0x00000001032826d4 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43799792 32 Behayve.iOS 0x00000001032889dc _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 43825144 33 Behayve.iOS 0x00000001031a6d98 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 42900404 34 Behayve.iOS 0x0000000103363c18 xamarin_log + 6012 35 Behayve.iOS 0x00000001008ff724 _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_ + 271680 36 libdyld.dylib 0x00000001ab773800 876FB49A-BFBA-37BF-AD37-6FFC90F7F981 + 6144
Launched at
May 1, 3:12 PM
Country
N/A
Device
iPad (7th gen, Wi-Fi)
Network
N/A
Crashed after
8s
Language
English
OS
iOS 13.4.1
User ID
N/A

**Comment by BillFulton** [comment]
The same  crash, with the same device type and presumably the same user, was reported on AppCenter on May 1, May 3, May 4 and May 5 - kind of strange. Always within a few seconds of launching the app.

Although not shown above, the log header is:
InAppPurchases+<>c__DisplayClass13_0.<InitialiseRevenueCatAsync>b__0 ().

**Comment by thisisthekap** [comment]
Please try to symbolicate your crashes (https://learn.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication).

**Comment by BillFulton** [comment]
Mmmmm. I don't know what's wrong with me, but have been trying to get my crashes symbolicated for the last two years with no success  :(  Everybody else seems to be able to. Well, I'll try again. I always keep the mSYMs.

**Comment by thisisthekap** [comment]
@BillFulton I think I can help you on that one. Please reach out to me on https://app.gitter.im (my name there is @thisisthekap-555da68115522ed4b3e0b73e:gitter.im)

**Comment by BillFulton** [comment]
Hey thanks very much!! I will, as soon as I get the current release out in the next few days.

**Comment by BillFulton** [comment]
It says:

@thisisthekap-555da68115522ed4b3e0b73e:gitter.im)

Send your first message to invite @thisisthekap-555da68115522ed4b3e0b73e:gitter.im) to chat

and when I send a message, it says "Some of your messages have not been sent". Retries result in the same error message.

**Comment by BillFulton** [comment]
Hi thisisthekap

I managed to get iOS symbolification working now. But thanks for the offer of help!

Cheers
Bill

**Comment by thisisthekap** [comment]
Closing this one for now. Feel free to ping me if it becomes apparent again.
